### ISSUE TITLE
Original firmwares (for recovery)

### ISSUE THREAD

**Issue by prosper00** [Lymes/cxg-e60wt#2]
I have a CXGE110WT. Seems readout protection is not enabled, and I was apparently able to make a copy of the existing firmwares.

Message me if you need them

**Comment by pav1388** [comment]
Hello. you can send it by e-mail: *****. I'll post it in the profile topic on the soldering iron, since people ask about the possibility of returning to the stock firmware

**Comment by prosper00** [comment]
actually, I need to delete this.... something's odd. The firmwares appear to download, but when I hexedit the files, they're blank

**Comment by pav1388** [comment]
:(
